# Generated by Django 2.2.1 on 2019-06-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20190612_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='portal',
            name='country',
            field=models.CharField(default='UAE', max_length=200),
            preserve_default=False,
        ),
    ]
