# Generated by Django 2.2.1 on 2019-07-01 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_portal_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portal',
            name='user',
        ),
    ]
